### ISSUE TITLE
Add Blacklist3r.py Telerik_knownkey.py Symfony_knownkey.py and bbot in bin directory

### ISSUE THREAD

**Issue by D3vil0p3r** [blacklanternsecurity/badsecrets#129]
@liquidsec @cosad3s  Since the mentioned scripts are stored in `/usr/lib/python3.xx` folder, is it possible to make the python installer to install in `/usr/bin` not only `badsecrets` as you did but also `blacklist3r` `telerik-knownkey` `symfony-knownkey` and `bbot`?

Currently I'm building and installing badsecrets as:
```
build() {
  cd $pkgname

  python -m build --wheel --outdir="$startdir/dist"
}

package() {
  cd $pkgname

  pip install \
    --verbose \
    --disable-pip-version-check \
    --no-warn-script-location \
    --ignore-installed \
    --no-compile \
    --no-deps \
    --root="$pkgdir" \
    --prefix=/usr \
    --no-index \
    --find-links="file://$startdir/dist" \
    $pkgname
}
```

**Comment by liquidsec** [comment]
Yeah, I think we can do this for `telerik-knownkey` `symfony-knownkey`. I don't want to do it for `blacklist3r` - for one its the same exact name as the actual `blacklist3r` tool. More importantly, all of it's functionality has since been added into the main tool, so its really just kept around as a reference/example for anyone who might want to use badsecrets as a library. BBOT is a separate tool of which badsecrets is actually a dependency.

**Comment by D3vil0p3r** [comment]
I agree

**Comment by liquidsec** [comment]
https://github.com/blacklanternsecurity/badsecrets/pull/131/commits/a3ce24776590810e50017bb58433daccf4fcfcab
